import type { Metadata } from 'next';
import '@/styles/globals.css';
import Providers from '@/app/providers';
import { pretendard } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Orury',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="viewport-fit=cover, width=device-width, initial-scale=1.0"
      />
      <body className={`${pretendard.className} antialiased bg-slate-100`}>
        <div className="max-w-[768px] mx-auto h-screen pb-safe bg-white">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
